updates

diff --git a/0x0C-web_server/0-transfer_file b/0x0C-web_server/0-transfer_file
--- a/0x0C-web_server/0-transfer_file
+++ b/0x0C-web_server/0-transfer_file
@@ -1,7 +1,26 @@
 #!/usr/bin/env bash
 # transfers a file from client to server
-if [ "$#" != "4" ]; then
+if [ "$#" != "4" ]
+then
    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
+   exit 1
+fi
+
+#assigning parameters to variables
+
+path_to_the_file=$1
+ip=$2
+username=$3
+path_to_ssh_keys=$4
+
+# disabling strict host key checking
+
+scp -o "StrictHostKeyChecking=no" -i "$path_to_file" "$username@$ip:=/"
+
+# checking if the transfer was successful
+if [ $? -eq 0 ]
+then
+	echo "File was transfered successfully"
 else
-   scp -o StrictHostKeyChecking=no -i "$4" "$1" "$3"@"$2":~/
+	echo "file transfer failed"
 fi
